version: '2.1'

services:
  protonmail-bridge:
    image: oh_pm_bridge
    init: true
    # image: shenxn/protonmail-bridge
    # build:
    #  context: ./build
    #  dockerfile: Dockerfile
    container_name: pm_bridge
    ports:
      - 192.168.101.103:25:25/tcp
      # - 192.168.101.103:1143:143/tcp
    restart: unless-stopped
    stdin_open: true 
    tty: true
    volumes:
    - ${APPSDIR}/pm_bridge:/root
